### ISSUE TITLE
Provide Jar

### ISSUE THREAD

**Issue by yanickrochon** [hidekatsu-izuno/wmf2svg#1]
I need to test this, but this seems a lot of trouble; downloading and configuring Eclipse, etc. as I don't use this IDE or even Maven. Since Jar files are Unicode and you already mention Java 6+ as a requirement, why not providing an already compiled runnable version of this project?

The README is showing how to run the Jar, but does not tell how to generate it anyway.

**Comment by hidekatsu-izuno** [comment]
This project's runnable jar is provided on the maven central repository. So I don't think it is needed.
If you need it, you can download directly maven repository.
