### ISSUE TITLE
sometimes, wmf and svg content is not equal

### ISSUE THREAD

**Issue by Hxh188** [hidekatsu-izuno/wmf2svg#17]
sorry,  my english is not good!
48cf.wmf convert to 48cf.svg, svg content is not equal to 48cf.wmf that "..." convert to "l"
![image](https://github.com/hidekatsu-izuno/wmf2svg/assets/17246178/9da586a9-a1d3-4d18-a903-1756eaae57a8)
![image](https://github.com/hidekatsu-izuno/wmf2svg/assets/17246178/06a531e2-878b-4e7a-b2a2-0f85fe887eeb)

[wmf2svg.zip](https://github.com/hidekatsu-izuno/wmf2svg/files/11469353/wmf2svg.zip)

**Comment by hidekatsu-izuno** [comment]
These images look the same in my environment; the font for the L part is MT Extra. This font is a symbol font and is often used to display mathematical expressions in Windows.

e.g. https://learn.microsoft.com/ja-jp/typography/font-list/mt-extra

You probably do not have MT Extra fonts in your environment and need to install it. Or you replace other font and unicode char 
.

**Comment by Hxh188** [comment]
in microsoft word file, it shows "...", but svg content is "L", "..." is the right contents, is it ?

![image](https://github.com/hidekatsu-izuno/wmf2svg/assets/17246178/3fb0f6a9-22d0-4085-8163-f57655211d03)
![image](https://github.com/hidekatsu-izuno/wmf2svg/assets/17246178/db251bc4-ba7e-46f4-a2d4-43f9d2b52185)

**Comment by hidekatsu-izuno** [comment]
> in microsoft word file, it shows "...", but svg content is "L", "..." is the right contents, is it ?

Yes, this behaviour is correct. Symbol fonts map ASCII codes to other symbols. Therefore, in MT Extra, L is displayed as "...".
