### ISSUE TITLE
Using "maven package" produces empty JAR file

### ISSUE THREAD

**Issue by cjheath** [hidekatsu-izuno/wmf2svg#4]
Apologies in advance - I'm new to maven.

I cannot build a JAR file. "maven package" says no files are
marked for inclusion so the resultant JAR file is empty.

**Comment by eyalroz** [comment]
I'm also seeing the same problem - 2 years later.

**Comment by hidekatsu-izuno** [comment]
wmf2svg is a Ant project. you have to build with ant, not maven.

```
cd wmf2svg
ant
```

**Comment by eyalroz** [comment]
@hidekatsu-izuno : Could you mention this in the README.md ?

**Comment by hidekatsu-izuno** [comment]
I changed folder structure to be simple. And I added how to build by Apache ant.
I close this issue.
