### ISSUE TITLE
svg encoding error

### ISSUE THREAD

**Issue by xiaoLee1993** [hidekatsu-izuno/wmf2svg#8]
i have a formula wmf,   some symbols went wrong when it was converted to svg;

example:  ÷，π

it works on the windows browser

but not on the mobile side

**Comment by hidekatsu-izuno** [comment]
Maybe it caused by SYMBOL font. Generally it uses to write formulas. And it was not installed on most mobile platform.
But you can try to use -replace-symbol-font option as command line args.

**Comment by xiaoLee1993** [comment]
Thank you!

i added a remote font to SVG yesterday, but it was still wrong when it was converted to PNG.

like this:

`
Gdi. GetStyleElement (). The insertBefore (doc. CreateTextNode (@ the font - face "\ n \ n" +

"{\ n +"

"The font-family: Symbol; \ n "+

"SRC: url (" https://***.com/symbol.ttf"); \ n "+

"} "), gdi getStyleElement () getFirstChild ());
`


but it is correct after replace-symbol-font is used

That's cool!
